# Generated by Django 6.0.3 on 2026-03-19 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("screening", "Скрининг"),
                            ("interview", "Собеседование"),
                            ("offer", "Оффер"),
                            ("hired", "Нанят"),
                            ("rejected", "Отклонён"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отклика"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кандидат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название этапа"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "survey_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.surveytemplate",
                        verbose_name="Шаблон опроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап собеседования",
                "verbose_name_plural": "Этапы собеседований",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланировано"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="vacancies.application",
                        verbose_name="Отклик",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.survey",
                        verbose_name="Опрос",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.interviewstage",
                        verbose_name="Этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собеседование",
                "verbose_name_plural": "Собеседования",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vacancies.interviewstage",
                verbose_name="Текущий этап",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Должность")),
                ("description", models.TextField(verbose_name="Описание")),
                ("department", models.CharField(max_length=255, verbose_name="Отдел")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыта"),
                            ("on_hold", "Приостановлена"),
                            ("closed", "Закрыта"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата от"
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата до"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыта"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="interviewstage",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="vacancies.vacancy",
                verbose_name="Вакансия",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="vacancies.vacancy",
                verbose_name="Вакансия",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("vacancy", "candidate")},
        ),
    ]
